# Numpy Exercise

#### 1. Import the numpy package under the name  (★☆☆)

In [39]:
import numpy as np

#### 2. Print the numpy version and the configuration  (★☆☆)

In [40]:
print(np.__version__)
print(np.show_config())

1.16.5
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Vibhav Garg/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'D:/Vibhav Garg/Anaconda\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/Vibhav Garg/Anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', '

#### 3. Create a null vector of size 10 (★☆☆)

In [41]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆)

In [42]:
x=np.array([1,2,3,4,5,6,7,8,9])
print(np.size(x))

9


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [43]:
help(np.add(x,2))

Help on ndarray object:

class ndarray(builtins.object)
 |  ndarray(shape, dtype=float, buffer=None, offset=0,
 |          strides=None, order=None)
 |  
 |  An array object represents a multidimensional, homogeneous array
 |  of fixed-size items.  An associated data-type object describes the
 |  format of each element in the array (its byte-order, how many bytes it
 |  occupies in memory, whether it is an integer, a floating point number,
 |  or something else, etc.)
 |  
 |  Arrays should be constructed using `array`, `zeros` or `empty` (refer
 |  to the See Also section below).  The parameters given here refer to
 |  a low-level method (`ndarray(...)`) for instantiating an array.
 |  
 |  For more information, refer to the `numpy` module and examine the
 |  methods and attributes of an array.
 |  
 |  Parameters
 |  ----------
 |  (for the __new__ method; see Notes below)
 |  
 |  shape : tuple of ints
 |      Shape of created array.
 |  dtype : data-type, optional
 |      Any objec

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [44]:
a=np.zeros(10)
a[4]=1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [45]:
np.arange(10,49,1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [46]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [47]:
np.arange(0,9,1).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [48]:
np.nonzero(np.array([1,2,0,0,4,0]))

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [49]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [50]:
np.random.rand(3,3,3)

array([[[0.94772689, 0.98021162, 0.52820857],
        [0.96096862, 0.11066672, 0.41621015],
        [0.5502353 , 0.25106661, 0.26653395]],

       [[0.20055096, 0.9532243 , 0.55943103],
        [0.30856357, 0.35818736, 0.85374251],
        [0.90485778, 0.39525218, 0.58918435]],

       [[0.55829261, 0.4362522 , 0.06721115],
        [0.09762002, 0.13731035, 0.8268951 ],
        [0.5926234 , 0.24046414, 0.83811396]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [51]:
q=np.random.rand(10,10)
print(np.min(q))
print(np.max(q))

0.012737792344185928
0.9826155442711928


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [52]:
w=np.random.rand(30)
print(np.mean(w))

0.4666301166231147


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [53]:
w=np.ones((6,6),dtype=int)
w[1:-1,1:-1]=0
print(w)

[[1 1 1 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 1 1 1 1 1]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [54]:
np.pad(x,pad_width=1,mode='constant',constant_values=0)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [55]:
False

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [56]:
z=np.zeros((5,5))
z[1][0]=1
z[2][1]=2
z[3][2]=3
z[4][3]=4
print(z)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [57]:
c=np.zeros((8,8))
c[0::2,1::2]=1
c[1::2,::2]=1
print(c)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [58]:
s=np.arange(0,(6*7*8),1)
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [59]:
f=np.array([[0,1],[1,0]])
print (np.tile(f,(4,4)))

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [60]:
np.random.rand(5,5).flatten()

array([0.10707258, 0.38401816, 0.05506687, 0.96194386, 0.59322234,
       0.84205825, 0.27266129, 0.6298037 , 0.10822494, 0.54569831,
       0.01405717, 0.85580996, 0.3329176 , 0.66044135, 0.14255665,
       0.64328156, 0.87616232, 0.08107464, 0.428923  , 0.76060033,
       0.23492472, 0.80809823, 0.49317877, 0.51100987, 0.60478469])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [61]:
np.dtype([('R','u1'), ('G','u1'), ('B','u1'), ('A','u1')])

dtype([('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [62]:
np.dot(np.random.rand(5,3),np.random.rand(3,2))

array([[0.4930133 , 0.75257806],
       [0.27529997, 0.76431611],
       [0.50764413, 0.59378159],
       [0.36616525, 0.78346018],
       [0.46917229, 0.84683   ]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [63]:
a=np.arange(11)
m=(a>3) & (a<8)
a[m]*=-1
print(a)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [64]:
9
10

10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [65]:
####All expressions are legal except Z<Z>Z

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [66]:
#Runtime error
#Runtime error
z=[-2.14748365e+09]

#### 29. How to round away from zero a float array ? (★☆☆)

In [67]:
np.around([0.39,1.54,1.35])

array([0., 2., 1.])

#### 30. How to find common values between two arrays? (★☆☆)

In [68]:
np.intersect1d(np.array([0,10,20,40,80]),np.array([10,20,30]))

array([10, 20])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [69]:
Using try and catch()

SyntaxError: invalid syntax (<ipython-input-69-4af00fc5f364>, line 1)

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [70]:
False

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [71]:
import datetime 
today = datetime.date.today()
yesterday = today - datetime.timedelta(days = 1)
tomorrow = today + datetime.timedelta(days = 1) 
print('Yesterday : ',yesterday)
print('Today : ',today)
print('Tomorrow : ',tomorrow)

Yesterday :  2020-03-24
Today :  2020-03-25
Tomorrow :  2020-03-26


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [72]:
print("July, 2016")
print(np.arange('2016-07', '2016-08', dtype='datetime64[D]'))

July, 2016
['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [73]:
a=np.arange(0, 10, 1)
b=np.arange(0, 20, 2)
c=np.dot(np.add(a,b),-a/2)

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [74]:
print(np.tile(np.array([0,1,2,3,4]),(5,1)))

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [75]:
print(np.random.randint(10000000,size=10))

[9644593 1320658 6258023 9399582 2050126 2978171  368373  885397 5894708
 2783044]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [76]:
print(np.random.uniform(0,1,size=10))

[0.59523275 0.95255249 0.20173859 0.5773646  0.7265244  0.87210753
 0.55629521 0.29813973 0.46574089 0.23841591]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [77]:
print(np.sort(np.random.rand(10)))

[0.00191257 0.11805641 0.15144278 0.34152902 0.35599048 0.35985276
 0.40515302 0.87000606 0.91306411 0.99424659]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [78]:
#Using the sum() function

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [79]:
a=np.random.rand(10)
b=np.random.rand(10)
print(np.allclose(a,b))

False


#### 43. Make an array immutable (read-only) (★★☆)

In [80]:
print(tuple(a))

(0.665030938018192, 0.6974831117926508, 0.4374309796423532, 0.7783990313682768, 0.3200182725772328, 0.24702921499450348, 0.12411028554162107, 0.7066547786175222, 0.48756423328321274, 0.48293905391482017)


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [81]:
z= np.random.random((10,2))
x,y = z[:,0], z[:,1]
r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x)
print(r)
print(t)

[0.68440105 0.23025947 0.6783843  0.9011508  0.77548052 0.57416098
 0.48086199 0.75798229 0.98309523 0.35678885]
[1.38547447 0.60704128 1.42479435 0.40863632 0.18906683 1.55897095
 1.54710921 0.31082263 1.27673774 0.08698005]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [82]:
z=np.random.rand(10)
z[np.where(np.max(z))]=0
print(z)

[0.         0.33286812 0.02020129 0.16376909 0.28014601 0.93137151
 0.88520044 0.22302254 0.99383825 0.69443968]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

In [83]:
Z = np.zeros((10,10), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,10),np.linspace(0,1,10))
print(Z)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [84]:
cauchym = 1.0/(np.array([1,2,3,4]).reshape((-1,1))-np.array([5,6,7]))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [85]:
print(np.min(a))
print(np.max(a))

0.12411028554162107
0.7783990313682768


#### 49. How to print all the values of an array? (★★☆)

In [86]:
print (a)

[0.66503094 0.69748311 0.43743098 0.77839903 0.32001827 0.24702921
 0.12411029 0.70665478 0.48756423 0.48293905]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [87]:
z=np.arange(100)
print(z[(np.abs(z-np.random.uniform(0,100))).argmin()])

45


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [88]:
print(np.zeros(10,[('position',[('x',float,1),('y',float,1)]),('color',[('r',float,1),('g',float,1),('b',float,1)])]))

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [89]:
import scipy
import scipy.spatial
a=np.random.rand(100,2)
print(scipy.spatial.distance.cdist(a,a))

[[0.         0.62392494 0.35728949 ... 0.44002534 0.82335127 0.53136419]
 [0.62392494 0.         0.27709075 ... 0.89496717 0.69797816 0.18139047]
 [0.35728949 0.27709075 0.         ... 0.63136579 0.63273205 0.18076731]
 ...
 [0.44002534 0.89496717 0.63136579 ... 0.         0.69648049 0.73461819]
 [0.82335127 0.69797816 0.63273205 ... 0.69648049 0.         0.53902351]
 [0.53136419 0.18139047 0.18076731 ... 0.73461819 0.53902351 0.        ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [90]:
print(np.arange(10,dtype=np.float32).astype(np.int32,copy=False))

[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [91]:
import pickle
f=open('file.data','wb')
obj=np.array([['1', '2', '3', '4', '5'],['6', '', '', '7', '8'],[ '', '', '9', '10', '11']])
pickle.dump(obj,f)
f.close()
f=open('file.data','rb')
print(pickle.load(f))
f.close()

[['1' '2' '3' '4' '5']
 ['6' '' '' '7' '8']
 ['' '' '9' '10' '11']]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [92]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [93]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [94]:
n=10
p=3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print (Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [95]:
x=np.random.rand(5,10)
print(x-x.mean(axis=1).reshape(-1,1))

[[-0.1678536   0.0387488  -0.03339559 -0.13076681 -0.08882984 -0.23717152
  -0.00280631  0.49942457  0.4927719  -0.3701216 ]
 [-0.03843351 -0.11799184 -0.09687354  0.52368573 -0.31609664  0.10798662
  -0.11949925 -0.04493567 -0.19676775  0.29892585]
 [ 0.38582598  0.24498817 -0.13709245 -0.04960407  0.07046886 -0.43206858
   0.33970088 -0.35881172  0.17236354 -0.23577061]
 [ 0.30835857  0.32199851 -0.36382242 -0.09815366 -0.34065434  0.24138518
  -0.3083901   0.22856746 -0.15274581  0.16345661]
 [-0.33727778 -0.03060931  0.45994862  0.46088369  0.05870547 -0.26816231
   0.15698176  0.06702657 -0.20119188 -0.36630484]]


#### 59. How to sort an array by the nth column? (★★☆)

In [96]:
z=np.random.randint(0,10,(3,3))
print(z)
print(z[z[:,1].sort()])

[[1 8 0]
 [4 8 0]
 [3 3 5]]
[[[1 3 0]
  [4 8 0]
  [3 8 5]]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [97]:
z=np.random.randint(0,10,(3,3))
print(z)
print((~z.any(axis=0)).any())

[[4 7 7]
 [5 7 9]
 [2 4 0]]
False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [98]:
Z=np.random.randint(0,10,10)
z=input()
print(Z.flat[np.abs(Z-z).argmin()])

0.5


TypeError: ufunc 'subtract' did not contain a loop with signature matching types dtype('<U11') dtype('<U11') dtype('<U11')

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [99]:
a=np.arange(0,3).reshape(1,3)
b=np.arange(6,9).reshape(3,1)
np.add(a,b)

array([[ 6,  7,  8],
       [ 7,  8,  9],
       [ 8,  9, 10]])

#### 63. Create an array class that has a name attribute (★★☆)

In [100]:
class array(object):
    def array(self):
        self.dat=np.arange(0,199)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [101]:
np.add(np.ones(10),np.bincount(np.random.randint(0,10,20),minlength=10))

array([1., 3., 6., 4., 4., 1., 1., 3., 2., 5.])

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [102]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

In [103]:
I = np.random.randint(0,2,(16,16,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [104]:
A = np.random.randint(0,10,(3,4,3,4))
print(A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1))

[[54 36 48 57]
 [44 41 65 59]
 [46 60 50 63]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [105]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
print(np.bincount(S,weights=D)/np.bincount(S))

[0.38393163 0.40800255 0.41267615 0.45795692 0.61028644 0.44919961
 0.57634378 0.39473129 0.31654714 0.54192527]


#### 69. How to get the diagonal of a dot product? (★★★)

In [106]:
np.diag(np.dot(np.random.randint(0,10,(3,3)),np.random.randint(0,10,(3,3))))

array([ 74,  31, 102])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [107]:
a=np.array([1,2,3,4,5])
z=np.zeros(17)
z[::4]=a
print(z)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [108]:
print(np.dot(np.ones((5,5)),np.ones((5,5,3))))

[[[5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]]

 [[5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]]

 [[5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]]

 [[5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]]

 [[5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]
  [5. 5. 5.]]]


#### 72. How to swap two rows of an array? (★★★)

In [109]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [110]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 4, 48) ( 4, 86) ( 7, 62) ( 7, 96) (10, 35) (10, 73) (12, 21) (12, 98)
 (15, 24) (15, 34) (21, 98) (24, 34) (35, 43) (35, 58) (35, 73) (40, 45)
 (40, 78) (43, 54) (43, 58) (43, 67) (45, 78) (48, 86) (49, 56) (49, 82)
 (54, 67) (56, 58) (56, 82) (56, 93) (58, 93) (62, 96)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [111]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [112]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

In [113]:
a=np.arange(10)
window=3
shape = (a.size - window + 1, window)
strides = (a.itemsize, a.itemsize)
print(np.lib.stride_tricks.as_strided(a, shape=shape, strides=strides))

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [114]:
#For boolean
Z = np.random.randint(0,2,100)
print ('original: ')
print (Z)
print('Negating a boolean: ')
print(np.logical_not(Z, out=Z))
#For float
Z = np.random.uniform(-1.0,1.0,10)
print ('original: ')
print (Z)
print ('Change the sign of float inplace: ')
print(np.negative(Z, out=Z))

original: 
[0 1 0 0 1 0 1 1 1 0 1 0 1 1 1 0 1 1 0 0 0 1 0 0 1 1 0 0 0 1 1 1 1 1 1 0 0
 0 0 0 1 0 0 1 1 0 1 1 0 1 0 1 1 1 0 1 1 1 0 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1
 0 1 1 0 0 0 1 0 0 1 1 0 1 1 1 0 0 0 1 0 1 1 1 0 0 0]
Negating a boolean: 
[1 0 1 1 0 1 0 0 0 1 0 1 0 0 0 1 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 0 0 0 0 1 1
 1 1 1 0 1 1 0 0 1 0 0 1 0 1 0 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0
 1 0 0 1 1 1 0 1 1 0 0 1 0 0 0 1 1 1 0 1 0 0 0 1 1 1]
original: 
[-0.04481428  0.06873837  0.33586862  0.77727371 -0.39227458  0.30264026
 -0.29785475  0.24966638 -0.75926553  0.20192093]
Change the sign of float inplace: 
[ 0.04481428 -0.06873837 -0.33586862 -0.77727371  0.39227458 -0.30264026
  0.29785475 -0.24966638  0.75926553 -0.20192093]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [115]:
P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
T=P0-P1
L = (T**2).sum(axis=1)
U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
U = U.reshape(len(U),1)
D = P0 + U*T - p
print(np.sqrt((D**2).sum(axis=1)))

[4.55199065 3.49692722 2.24053266 3.55817874 3.91828314 1.77323806
 5.84179524 2.18549973 8.80247294 0.47031704]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [116]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))
P0 = np.random.uniform(-10, 10, (5,2))
P1 = np.random.uniform(-10,10,(5,2))
p = np.random.uniform(-10, 10, (5,2))
print (np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 1.61349851  6.86650765  4.17570317  5.29568342  1.88461041]
 [ 2.6832716   7.8794908   4.83025546  6.08719934  2.66320094]
 [ 4.59189254  9.92765877  5.52988574  7.9479772   3.65374896]
 [ 6.96873049 10.0930206  11.03741974  5.82280495  8.83417167]
 [ 0.13562603  1.34277581 10.62274738  3.20144761  7.01105814]]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

In [117]:
Z = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
window=4
shape = (Z.size - window + 1, window)
strides = (Z.itemsize, Z.itemsize)
print(np.lib.stride_tricks.as_strided(Z, shape=shape, strides=strides))

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [118]:
Z = np.arange(0,100).reshape(10,10)
np.linalg.matrix_rank(Z)

2

#### 83. How to find the most frequent value in an array?

In [119]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

8


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [120]:
Z=np.random.randint(0,100,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = np.lib.stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[97 57 20]
   [10 10 42]
   [27 91  6]]

  [[57 20 56]
   [10 42 81]
   [91  6 31]]

  [[20 56 85]
   [42 81 73]
   [ 6 31 23]]

  [[56 85 92]
   [81 73 42]
   [31 23 29]]

  [[85 92 64]
   [73 42 91]
   [23 29 90]]

  [[92 64 14]
   [42 91 21]
   [29 90 35]]

  [[64 14  9]
   [91 21 81]
   [90 35 48]]

  [[14  9 53]
   [21 81 67]
   [35 48  9]]]


 [[[10 10 42]
   [27 91  6]
   [ 8 72 65]]

  [[10 42 81]
   [91  6 31]
   [72 65 35]]

  [[42 81 73]
   [ 6 31 23]
   [65 35 26]]

  [[81 73 42]
   [31 23 29]
   [35 26 53]]

  [[73 42 91]
   [23 29 90]
   [26 53 17]]

  [[42 91 21]
   [29 90 35]
   [53 17 97]]

  [[91 21 81]
   [90 35 48]
   [17 97 67]]

  [[21 81 67]
   [35 48  9]
   [97 67 94]]]


 [[[27 91  6]
   [ 8 72 65]
   [71 86 60]]

  [[91  6 31]
   [72 65 35]
   [86 60 15]]

  [[ 6 31 23]
   [65 35 26]
   [60 15 12]]

  [[31 23 29]
   [35 26 53]
   [15 12 99]]

  [[23 29 90]
   [26 53 17]
   [12 99 78]]

  [[29 90 35]
   [53 17 97]
   [99 78 39]]

  [[90 35 48]
   [17 97 67]


#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

In [121]:
class Symetric(np.ndarray):
    def __setitem__(self,i,j, value):
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)
def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)
S = symetric(np.random.randint(0,10,(5,5)))
print(S)

[[ 6 14  4  9  7]
 [14  4 16  6  2]
 [ 4 16  6 10  8]
 [ 9  6 10  3 10]
 [ 7  2  8 10  9]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [122]:
print(np.tensordot(np.ones((10,20,20)), np.ones((10,20,1)), axes=[[0, 1], [0, 1]]))

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [123]:
Z = np.ones((16,16))
print(np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], 4), axis=0),np.arange(0, Z.shape[1], 4), axis=1))

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [124]:
def iterate(Z):
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print (Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★)

In [125]:
x = np.arange(10)
np.random.shuffle(x)
n=5
print (x[np.argsort(x)[-n:]])

[5 6 7 8 9]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [126]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)
    ix = np.indices(shape, dtype=int).reshape(len(arrays), -1).T
    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]
    return ix
print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [128]:
Z = np.array([('Hello', 2.5, 3),
              ('World', 3.6, 2)])
R = np.core.records.fromarrays(Z.T,names='col1, col2, col3',
                                   formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [131]:
x=np.random.rand(5,7)
print(np.power(x,3))
print(x*x*x)
print(np.einsum('i,i,i->i',x,x,x,[Ellipsis,...]))

[[2.07022428e-02 1.43164417e-01 6.46989878e-02 4.31110400e-01
  6.02236811e-02 4.58784999e-03 5.84582431e-01]
 [4.42715717e-03 6.25311665e-03 5.02614517e-02 1.31839603e-01
  5.84653351e-05 2.88837298e-05 6.66410216e-03]
 [7.67577388e-02 3.35643558e-02 5.03001748e-01 5.35008499e-02
  8.00813629e-01 6.38044571e-02 5.51578940e-01]
 [1.39069829e-01 5.90975400e-01 7.32229258e-01 9.31607376e-01
  3.79272519e-01 3.76585289e-01 4.63340248e-02]
 [1.41937808e-02 8.13365349e-02 1.88849104e-03 2.25434656e-02
  7.36971799e-02 4.23267190e-01 4.82269911e-01]]
[[2.07022428e-02 1.43164417e-01 6.46989878e-02 4.31110400e-01
  6.02236811e-02 4.58784999e-03 5.84582431e-01]
 [4.42715717e-03 6.25311665e-03 5.02614517e-02 1.31839603e-01
  5.84653351e-05 2.88837298e-05 6.66410216e-03]
 [7.67577388e-02 3.35643558e-02 5.03001748e-01 5.35008499e-02
  8.00813629e-01 6.38044571e-02 5.51578940e-01]
 [1.39069829e-01 5.90975400e-01 7.32229258e-01 9.31607376e-01
  3.79272519e-01 3.76585289e-01 4.63340248e-02]
 [1.41937

ValueError: operand has more dimensions than subscripts given in einstein sum, but no '...' ellipsis provided to broadcast the extra dimensions.

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [ ]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))
C = (A[..., np.newaxis, np.newaxis] == B)
rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
print(rows)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [132]:
Z = np.random.randint(0,4,(10,3))
E = np.logical_and.reduce(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(Z)
print(U)

[[1 1 0]
 [2 3 3]
 [0 2 3]
 [3 0 1]
 [3 3 3]
 [3 3 2]
 [3 0 0]
 [2 2 2]
 [0 2 3]
 [2 1 3]]
[[1 1 0]
 [2 3 3]
 [0 2 3]
 [3 0 1]
 [3 3 2]
 [3 0 0]
 [0 2 3]
 [2 1 3]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [133]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128, 257], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [134]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [140]:
a=np.random.randint(0,5,(5,5))
b=np.random.randint(4,9,(5,5))
#inner_a=np.einsum('i,i',a,a)
#inner_b=np.einsum('i,i',b,b)
#outer=np.einsum('i,j',a,b)
#sum_a=np.einsum('ij->i',a)
#sum_b=np.einsum('ij->i',b)
#mul=np.einsum('ij,j',a,b)
print(a)
print(b)

[[3 1 2 2 0]
 [0 4 1 3 0]
 [0 3 4 1 3]
 [4 0 0 3 2]
 [3 2 3 3 4]]
[[6 6 8 5 8]
 [4 7 8 8 6]
 [7 6 8 7 6]
 [7 7 6 5 8]
 [8 7 8 5 5]]


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [142]:
x=np.random.randint(0,5,(6,3))
n=10
c=(np.sum(x,axis=1))==n
print(x)
print(x[c])

[[3 0 1]
 [4 4 3]
 [4 2 2]
 [1 3 3]
 [4 3 1]
 [1 2 0]]
[]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [144]:
n=6
m=np.zeros(n)
for i in range(n):
    x=np.arange(0,10)
    c=np.random.choice(x)
    x[np.where(x==c)]=np.random.randint(10,19,1)
    m[i]=np.mean(x)
print(m)

[5.5 5.3 5.4 5.1 5.5 5. ]
